---
required: ["init_lib", "data_lib", "db", "passwd", "user_name", "host", "db_name", "startup_cmd"]
should_exist: ["init_lib", "data_lib"]
init_lib: /home/Squirrel/data/fuzz_root/pqsql_init_lib
data_lib: /home/Squirrel/data/fuzz_root/pqsql_data_lib
db: postgresql
passwd: ''
user_name: dobigthing
db_name: postgres
host: localhost
port: 5433
startup_cmd: "/usr/local/pgsql/bin/postgres -D /home/for_showmap/pgsql/data -p 5433 &"